title: Bogdan Guranda
description: Personal website
baseurl: ""
url: "https://bogdanguranda.github.io/"
permalink: pretty

author:
  name: Bogdan Guranda
  linkedin: bogdan-guranda
  github: bogdanguranda

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: category
  - scope:
      path: ""
    values:
      layout: category

nav:
  - title: Apps
    url: /apps/
    subnav:
      - title: Games
        url: /apps/games/
        subnav:
          - title: Logikids (Bachelor's Degree Thesis)
            url: /apps/games/logikids/
          - title: Sokobug
            url: /apps/games/sokobug/
      - title: Finance
        url: /apps/finance/
        subnav:
          - title: Deep Dive
            url: /apps/finance/deep-dive/
          - title: Trading Assistant
            url: /apps/finance/trading-assistant/
          - title: Trading Assistant Discord Bot
            url: /apps/finance/trading-assistant-discord-bot/
      - title: Other
        url: /apps/other/
        subnav:
          - title: Aphorisms Generator
            url: /apps/other/aphorisms-generator/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /
